# 服务器监听
server:
  address: 0.0.0.0
  port: 8080
  ssl: # HTTPS配置
    key-store: classpath:keystore/library.p12 # 密钥文件名
    key-alias: library # 密钥别名
    key-store-password: sund!@123 # cmd命令执行过程中输入的密码
# JWT Secret
jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5

# actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  thymeleaf:
    cache: false # thymeleaf的缓存关闭
  datasource:
    # 数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:30102/exam?useUnicode=true&characterEncoding=utf8&autoReconnect=true&&useSSL=false
    username: root
    password: 123456

    # 初始化SQL脚本
    schema: classpath:db/script/schema.sql
    data: classpath:db/script/data.sql
    initialization-mode: ALWAYS
    sql-script-encoding: UTF-8
    continue-on-error: true

    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j

    # 连接池的设置
    druid:
      initial-size: 8 #初始化时建立物理连接的个数
      max-active: 20 #最大连接池数量 maxIdle已经不再使用
      min-idle: 1 #最小连接池数量
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20 #当值大于0时poolPreparedStatements会自动修改为true
      validation-query: select 'x' FROM DUAL #用来检测连接是否有效的sql 必须是一个查询语句
      validation-query-timeout: 2000 #用来检测连接是否有效的sql 必须是一个查询语句,设置查询超时时间
#      exception-sorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000 #既作为检测的间隔时间又作为testWhileIdel执行的依据
      min-evictable-idle-time-millis: 3000000 #销毁线程时检测当前连接的最小空闲时间(毫秒)，关闭当前连接
      max-evictable-idle-time-millis: 6000000 #销毁线程时检测当前连接的最大空闲时间(毫秒)，关闭当前连接
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      stat-view-servlet: #设置访问druid监控页的账号和密码,默认没有 http://127.0.0.1:8080/druid/sql.html
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        reset-enable: false
  redis:
    host: 127.0.0.1
    port: 16379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8 #最大连接数(负数表示没有限制)
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100000 #最大阻塞等待时间(负数表示没有限制)
mybatis:
  mapperLocations: classpath*:db/mapper/*.xml

# 自定义HTTP请求配置
custom:
  rest:
    connection:
      connection-request-timeout: 3000
      connect-timeout: 3000
      read-timeout: 3000